import { NodePropertyTypes } from "n8n-workflow";
import { USER_METHODS } from "../../utils/constants/methods_constants";
import { USER_INVITATIONS_METHODS } from "../../utils/constants/methods_constants";

export let APPS_FIELDS = {
    displayName: 'Apps fields to get on response',
    name: 'appsFields',
    type: 'multiOptions' as NodePropertyTypes,
    options: [
        { name: 'accessibilityUrl', value: 'accessibilityUrl' },
        { name: 'name', value: 'name' },
        { name: 'bundleId', value: 'bundleId' },
        { name: 'sku', value: 'sku' },
        { name: 'primaryLocale', value: 'primaryLocale' },
        { name: 'isOrEverWasMadeForKids', value: 'isOrEverWasMadeForKids' },
        { name: 'subscriptionStatusUrl', value: 'subscriptionStatusUrl' },
        { name: 'subscriptionStatusUrlVersion', value: 'subscriptionStatusUrlVersion' },
        { name: 'subscriptionStatusUrlForSandbox', value: 'subscriptionStatusUrlForSandbox' },
        { name: 'subscriptionStatusUrlVersionForSandbox', value: 'subscriptionStatusUrlVersionForSandbox' },
        { name: 'contentRightsDeclaration', value: 'contentRightsDeclaration' },
        { name: 'streamlinedPurchasingEnabled', value: 'streamlinedPurchasingEnabled' },
        { name: 'accessibilityDeclarations', value: 'accessibilityDeclarations' },
        { name: 'appEncryptionDeclarations', value: 'appEncryptionDeclarations' },
        { name: 'ciProduct', value: 'ciProduct' },
        { name: 'betaTesters', value: 'betaTesters' },
        { name: 'betaGroups', value: 'betaGroups' },
        { name: 'appStoreVersions', value: 'appStoreVersions' },
        { name: 'preReleaseVersions', value: 'preReleaseVersions' },
        { name: 'betaAppLocalizations', value: 'betaAppLocalizations' },
        { name: 'builds', value: 'builds' },
        { name: 'betaLicenseAgreement', value: 'betaLicenseAgreement' },
        { name: 'betaAppReviewDetail', value: 'betaAppReviewDetail' },
        { name: 'appInfos', value: 'appInfos' },
        { name: 'appClips', value: 'appClips' },
        { name: 'appPricePoints', value: 'appPricePoints' },
        { name: 'endUserLicenseAgreement', value: 'endUserLicenseAgreement' },
        { name: 'appPriceSchedule', value: 'appPriceSchedule' },
        { name: 'appAvailabilityV2', value: 'appAvailabilityV2' },
        { name: 'inAppPurchases', value: 'inAppPurchases' },
        { name: 'subscriptionGroups', value: 'subscriptionGroups' },
        { name: 'gameCenterEnabledVersions', value: 'gameCenterEnabledVersions' },
        { name: 'perfPowerMetrics', value: 'perfPowerMetrics' },
        { name: 'appCustomProductPages', value: 'appCustomProductPages' },
        { name: 'inAppPurchasesV2', value: 'inAppPurchasesV2' },
        { name: 'promotedPurchases', value: 'promotedPurchases' },
        { name: 'appEvents', value: 'appEvents' },
        { name: 'reviewSubmissions', value: 'reviewSubmissions' },
        { name: 'subscriptionGracePeriod', value: 'subscriptionGracePeriod' },
        { name: 'customerReviews', value: 'customerReviews' },
        { name: 'customerReviewSummarizations', value: 'customerReviewSummarizations' },
        { name: 'gameCenterDetail', value: 'gameCenterDetail' },
        { name: 'appStoreVersionExperimentsV2', value: 'appStoreVersionExperimentsV2' },
        { name: 'alternativeDistributionKey', value: 'alternativeDistributionKey' },
        { name: 'analyticsReportRequests', value: 'analyticsReportRequests' },
        { name: 'marketplaceSearchDetail', value: 'marketplaceSearchDetail' },
        { name: 'backgroundAssets', value: 'backgroundAssets' },
        { name: 'betaFeedbackScreenshotSubmissions', value: 'betaFeedbackScreenshotSubmissions' },
        { name: 'betaFeedbackCrashSubmissions', value: 'betaFeedbackCrashSubmissions' },
        { name: 'webhooks', value: 'webhooks' }
    ],
    default: [],
    description: 'The fields of the games that you want to get on the request',
    displayOptions: {
        show: {
            operation: [USER_METHODS.READ_USER_INFORMATION,
                USER_INVITATIONS_METHODS.LIST_ALL_APPS_VISIBLE_TO_AN_INVITED_USER,
            ],
        },
    },
};
